---
- include: install.yml
  when: is_redundancy

- include: configure.yml
  when: is_redundancy and hostvars[inventory_hostname].is_first_active_node == "active"

- include: firewalld.yml
  when: is_redundancy

- include: service.yml
  when: is_redundancy

- include: cluster_property.yml
  when: is_redundancy and hostvars[inventory_hostname].is_first_active_node == "active"

