---
- name: Start db service
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - name: mariadb
      state: started
  ignore_errors: yes
  changed_when: false

- name: Set password of root user
  shell: mysql -h localhost -e "set password for 'root'@'localhost'=password('i-portal');"
  ignore_errors: yes

- name: Check existing database
  shell: mysql -h localhost -pi-portal -e "show databases;" | grep scheduler
  register: result_database
  changed_when: false
  ignore_errors: yes

- name: Create database
  shell: mysql -h localhost -pi-portal -e "create database scheduler;"
  when: result_database.stdout == ""

- name: Copy init-schedulerdb script
  template:
    src: init-schedulerdb.sh.j2
    dest: "{{ packages.work_path }}/init-schedulerdb.sh"
  register: result_script

- name: Set database user
  shell: sh {{ packages.work_path }}/init-schedulerdb.sh
  when: result_script.changed

