---
- name: Restart Apache for active node
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - name: httpd
      state: restarted
  when: hostvars[inventory_hostname].is_first_active_node == "active"

