---
- name: <FE> Check ping to lb
  shell: |
    ping -c 1 {{ item }}
  changed_when: false
  with_items:
    - "{{ nal.lb.nodes[0].svmng_ip }}"
    - "{{ nal.lb.nodes[1].svmng_ip }}"
    - "{{ nal.lb.fip.ip }}"

